import { Router } from "express";
import activationRoutes from "./activationRoutes.js";
import adminRoutes from "./adminRoutes.js";
import authRoutes from "./authRoutes.js";
import clientRoutes from "./clientRoutes.js";
import chatRoutes from "./chatRoutes.js";
import healthRoutes from "./healthRoutes.js";
import contentRoutes from "./contentRoutes.js";
import leadRoutes from "./leadRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import operationsRoutes from "./operationsRoutes.js";
import paymentRoutes from "./paymentRoutes.js";
import serviceRoutes from "./serviceRoutes.js";
import smartCardRoutes from "./smartCardRoutes.js";
import scratchCardRoutes from "./scratchCardRoutes.js";
import ticketRoutes from "./ticketRoutes.js";
import uploadRoutes from "./uploadRoutes.js";
import localizationRoutes from "./localizationRoutes.js";
import vpnRoutes from "./vpnRoutes.js";

const router = Router();

router.use("/health", healthRoutes);
router.use("/content", contentRoutes);
router.use("/auth", authRoutes);
router.use("/localization", localizationRoutes);
router.use("/vpn", vpnRoutes);
router.use("/leads", leadRoutes);
router.use("/notifications", notificationRoutes);
router.use("/operations", operationsRoutes);
router.use("/payments", paymentRoutes);
router.use("/services", serviceRoutes);
router.use("/cards", smartCardRoutes);
router.use("/scratch", scratchCardRoutes);
router.use("/activations", activationRoutes);
router.use("/tickets", ticketRoutes);
router.use("/admin", adminRoutes);
router.use("/client", clientRoutes);
router.use("/uploads", uploadRoutes);
router.use("/chat", chatRoutes);

export default router;
